version: '3.8'

services:
  hair-orama:
    container_name: app
    image: app:dev
    build:
      context: .
      dockerfile: ./apps/hair-orama/docker/Dockerfile
    ports:
      - '4200:4200'
    volumes:
      - .:/usr/src/app:cached
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    extra_hosts:
      - 'hair-orama.local:127.0.0.1'
