version: '3.8'

services:
  hair-orama:
    container_name: app
    image: hair-orama/app:dev
    build:
      context: .
      dockerfile: ./apps/hair-orama/docker/Dockerfile
    ports:
      - '4200:4200'
    volumes:
      - .:/usr/src/app:cached
      - /usr/src/app/node_modules
      - ./nginx/ssl:/etc/nginx/ssl
    environment:
      - CHOKIDAR_USEPOLLING=true
    extra_hosts:
      - 'hair-orama.local:127.0.0.1'
    # command: ['npx', 'nx', 'serve', 'hair-orama', '--host', 'hair-orama.local']
    networks:
      - default

  flask-app:
    container_name: api
    image: hair-orama/api:dev
    build: 
      context: .
      dockerfile: ./apps/Backend/Dockerfile
    ports:
      - '5000:5000'
    environment:
      - MYSQL_HOST=mysql-db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_DB=flaskdb
    depends_on:
      - mysql-db
    volumes:
      - ./apps/Backend:/app

  mysql-db:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: flaskdb
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - default

networks:
  default:
    driver: bridge
volumes:
  mysql-data:
