version: '3.8'

services:
  app:
    container_name: app
    image: app:dev
    build:
      context: .
      dockerfile: ./apps/hair-orama/docker/Dockerfile
    volumes:
      - .:/usr/src/app:cached
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    extra_hosts:
      - 'hair-orama.local:0.0.0.0'
    depends_on:
      - api
    networks:
      - internal-net

  api:
    container_name: api
    image: api:dev
    build:
      context: .
      dockerfile: ./apps/Backend/Dockerfile
    environment:
      - MYSQL_HOST=mysql-db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_DB=flaskdb
    extra_hosts:
      - 'hair-orama.local:0.0.0.0'
    depends_on:
      - mysql-db
    volumes:
      - ./apps/Backend:/app
    networks:
      - internal-net

  mysql-db:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: flaskdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - internal-net

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - '8080:443'
      - '4200:443'
      - '5000:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
      - api
      - mysql-db
    networks:
      - internal-net

networks:
  internal-net:

volumes:
  mysql-data:
